version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /examples/appdir
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /examples/custom-filename
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /examples/pagesdir
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/next-typesafe-url
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /www/docs
    schedule:
      interval: daily
